### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by ingwild** [ivgur/ipv6_sort#1]
```
$ RUST_BACKTRACE=1 ./ipv6_sort --help
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /builddir/build/BUILD/rustc-1.36.0-src/src/libcore/slice/mod.rs:2695:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: <usize as core::slice::SliceIndex<[T]>>::index
             at /builddir/build/BUILD/rustc-1.36.0-src/src/libcore/slice/mod.rs:2695
  10: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /builddir/build/BUILD/rustc-1.36.0-src/src/libcore/slice/mod.rs:2552
  11: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /builddir/build/BUILD/rustc-1.36.0-src/src/liballoc/vec.rs:1687
  12: ipv6_sort::main
             at src/main.rs:13
  13: std::rt::lang_start::{{closure}}
             at /builddir/build/BUILD/rustc-1.36.0-src/src/libstd/rt.rs:64
  14: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  16: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  17: std::rt::lang_start
             at /builddir/build/BUILD/rustc-1.36.0-src/src/libstd/rt.rs:64
  18: main
  19: __libc_start_main
  20: <unknown>

```

**Comment by ingwild** [comment]
Now runs fine without arguments.

**Comment by ivgur** [comment]
Fixed by adding crate clap and parsing arguments with this crate.
